### ISSUE TITLE
meet error when running  python main_gcn.py --evaluate checkpoint/pretrained/hgcn_cpn_best.pth.tar --keypoints cpn_ft_h36m_cbb

### ISSUE THREAD

**Issue by CapenZen** [ZhimingZo/HGCN#1]
--keypoints cpn_ft_h36m_dbb
==> Using settings Namespace(actions='*', batch_size=256, checkpoint='checkpoint', dataset='h36m', downsample=1, dropout=0.0, epochs=50, evaluate='checkpoint/pretrained/hgcn_cpn_best.pth.tar', hid_dim=96, keypoints='cpn_ft_h36m_dbb', lr=0.001, lr_decay=100000, lr_gamma=0.8, max_norm=True, non_local=False, num_layers=4, num_workers=8, resume='', snapshot=5)
==> Loading dataset...
==> Preparing data...
==> Loading 2D detections...
==> Creating model...
Traceback (most recent call last):
  File "main_gcn.py", line 288, in <module>
    main(parse_args())
  File "main_gcn.py", line 104, in main
    nodes_group=dataset.skeleton().joints_group() if args.non_local else None).to(device)
TypeError: __init__() got an unexpected keyword argument 'nodes_group'

**Comment by CapenZen** [comment]
I just delete 'nodes_group' and fix it .
